name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 20 + pnpm via Corepack
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Prepare pnpm (Corepack)
        run: |
          corepack enable
          corepack prepare pnpm@10.4.1 --activate
          pnpm -v
      - name: Show versions
        run: |
          node -v
          corepack -v || true
      - name: Install deps (frozen lockfile)
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint || true
      - name: Build
        run: pnpm run build
